### ISSUE TITLE
Can not load codon alignments

### ISSUE THREAD

**Issue by Victaphanta** [BEAST2-Dev/codonsubstmodels#10]
Hi, Have been trying to load my alignments using the latest version of beast/beauti but keep getting the error "uncertain codon index >=64 is not supported".  Have check and all looks ok, but I think the issue has to do with missing data, coded with"-".  I also tried to load your xml example but unfortunately all will not load.  Hope you can help.

**Comment by walterxie** [comment]
Hi, this package is not supporting the uncertainty in the nucleotides at the moment. You have to provide the exact coded sequences. This err message is confusing. I will improve it. 

Only the XMLs produced by BEAUti can be loaded successfully. I have produced 1 example, and the rest of them are moved to a subfolder for testing purpose that would not be released.

<img width="860" alt="Screenshot 2023-03-23 at 3 16 10 PM" src="https://user-images.githubusercontent.com/5743014/227083334-ad6c0da5-d1e9-4c87-8d26-5f737fb61e35.png">
