### ISSUE TITLE
handle partial nucleotide ambiguities (i.e. -TA) 

### ISSUE THREAD

**Issue by walterxie** [BEAST2-Dev/codonsubstmodels#3]
such as -TA.

**Comment by walterxie** [comment]
Use the following XML:

`<data id="codon.alignment" data="@alignment" dataType="codon" geneticCode="vertebrateMitochondrial" spec="CodonAlignment" unknownCodeException="false"/>
`

**Comment by rbouckaert** [comment]
Should missing data not be treated as ambiguous characters?

**Comment by walterxie** [comment]
The problem was the `codeMap` of triplets could not handle partial nucleotide ambiguities (i.e. -TA), so that the `dataType.stringToEncoding(data)` would throw `IllegalArgumentException `:

```
if (map.containsKey(code)) {
	sequence.add(map.get(code));
} else {
	throw new IllegalArgumentException("Unknown code found in sequence: " + code);
}
```

One simple solution is to replace any triplets containing nucleotide ambiguities into 3 nucleotide ambiguities, namely a missing data in amino acid. I will change my confusing title.

**Comment by rbouckaert** [comment]
@walterxie that is what I understood, but should missing data not be treated as ambiguous characters: -TA implies there are 4 possible states
ATA
CTA
GTA
TTA
so it should be possible to interpret -TA as ambiguous for these 4 characters. Likewise when there are two missing characters, there are 16 ambiguous states. The codeMap may not be the best way to deal with ambiguities.

**Comment by walterxie** [comment]
Yes, codeMap is not enough to handle this complexity. The complexity not only ends to interpret -TA as ambiguous for these 4 characters, because it will make the calculation of the relative instantaneous substitution rate q_ij uncertain (https://github.com/BEAST2-Dev/codonsubstmodels).

I have no simple solution except of the fix of #3.

**Comment by alexeid** [comment]
It is a good initial solution.

But ambiguities are easy to handle from the perspective of the instantaneous rate matrix. There is nothing to do there, it is just how the partial likelihoods are initialised at the leaves of the tree. In the case of nucleotide models we have the following mappings: A -> [1,0,0,0]; C -> [0,1,0,0]; G -> [0,0,1,0]; T -> [0,0,0,1]; R -> [1,0,1,0]; Y -> [0,1,0,1]; N -> [1,1,1,1]; ? -> [1,1,1,1]; ‘-' -> [1,1,1,1].

So for codons you could have a similar mapping that just placed a 1 for every codon that your uncertain codon could be resolved to.

**Comment by walterxie** [comment]
@alexeid Two parts here:
1. define `codeMap` to parse sequences (triplets) into states;
2. compute rate matrix.

Your idea solves the 2nd, but the 1st is still complex, unless I list all ambiguous combinations (-AA, -CA, -TA, ...) in  `codeMap`, which is not a nice way.

**Comment by alexeid** [comment]
Wouldn’t that only add 60 more codes into the codeMap? 48 with two nucleotides and 12 with 1 nucleotide:

-A-, -C-, -G-, -T-, --A, --C, --G, --T, A--, C--, G--, T--

**Comment by walterxie** [comment]
x2 for ? or -

**Comment by alexeid** [comment]
I don’t know the details of the pipeline, but it might be worth doing some regularisation at an early point to avoid that.
