### ISSUE TITLE
Error on address from BEAUti2 Package Manager

### ISSUE THREAD

**Issue by migrau** [BEAST2-Dev/codonsubstmodels#6]
Not sure if this is the correct place but when trying to update from 1.1.1 to 1.1.2 using the BEAUti2 Package manager, the address from the default repository (https://raw.githubusercontent.com/CompEvol/CBAN/master/packages2.5.xml) is wrong:

`url="https://github.com/BEAST2-Dev/codonsubstmodels/releases/download/v1.1.1/CodonSubstModels.v1.1.2.zip"`

**Comment by rbouckaert** [comment]
Thanks for letting us know -- I fixed the link, so it should install now. Let me know if you run into any more trouble.

**Comment by migrau** [comment]
Working, thanks ;)
